modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "justanotherautototem"
version = "${version}"
displayName = "JustAnotherAutoTotem"
authors = "eirmax"
description = '''
Automatically change the pop totem to a new one
'''
logoFile = "assets/justanotherautototem/icon.png"

[[dependencies.justanotherautototem]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.justanotherautototem]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "justanotherautototem.mixins.json"
